name: go_transitions
description: "Easily create, combine and apply transitions to routes with GoTransitions."
version: 0.8.2
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/go_transitions.git
topics:
 - go-router
 - page
 - transition
 - transitions

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
  
dependencies:
  flutter:
    sdk: flutter
  go_router: '>=13.0.0 <18.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0